In [1]:
#1
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
display(df.head(10))

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
0,CUST101160,37,297809,698,Self-Employed,12th,Married,Mumbai,Mass,Education,378342,60,3,0.258,No
1,CUST100077,36,1048283,874,Contract,Graduate,Single,Jaipur,PREMIUM,Auto,751792,48,11,0.558,Yes
2,CUST100317,55,1043481,661,Self-Employed,Postgraduate,Married,Kolkata,Affluent,Auto,892792,84,4,NaN,Yes
3,CUST101041,54,369591,722,Salaried,Graduate,Single,Kolkata,Premium,Home,908250,84,10,0.356,Yes
4,CUST101358,27,666989,727,Self-Employed,Graduate,Married,Hyderabad,Mass,Education,386370,72,4,0.169,Yes
5,CUST100925,32,317590,690,Salaried,Graduate,M,Mumbai,Premium,Auto,235549,120,5,0.46,No
6,CUST100758,39,322966,707,Contract,Graduate,Married,Chennai,Mass,Personal,563319,24,7,0.323,No
7,CUST100793,54,999108,689,Salaried,Graduate,Divorced,Hyderabad,SME,Auto,767783,48,NaN,0.233,Yes
8,CUST100965,65,478191,758,Contract,Graduate,Divorced,Bengaluru,premium,Auto,753872,72,5,0.375,No
9,CUST101198,67,1063307,774,SALARIED,Graduate,Married,Jaipur,Affluent,Home,549693,120,2,0.394,Yes

In [2]:
#2
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
df.shape

(1535, 15)

In [7]:
#3
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
print("All columns names: ")
for column in df.columns:
    print(repr(column))
print("\nColumn names with leading/trailing spaces: ")
for column in df.columns:
    if column != column.strip():
        print(repr(column))

All columns names:
'Customer ID'
'Age'
'Annual Income'
'credit Score'
'Employment-Type'
'Education  Level'
'marital_status'
'city'
'customer_segment'
'loan_type'
'Loan Amount (INR)'
'tenure Months'
'Monthly Visits'
'debt_to_income'
'Loan Approved?'

Column names with leading/trailing spaces:

In [ ]:
#4
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')

In [8]:
#5
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
df.dtypes

Customer ID            str
Age                    str
Annual Income          str
credit Score           str
Employment-Type        str
Education  Level       str
marital_status         str
city                   str
customer_segment       str
loan_type              str
Loan Amount (INR)      str
tenure Months        int64
Monthly Visits         str
debt_to_income         str
Loan Approved?         str
dtype: object

In [9]:
#6
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
print("Total number of missing values in each column :")
print(df.isnull().sum())

Total number of missing values in each column :
Customer ID            0
Age                   71
Annual Income         84
credit Score          77
Employment-Type       60
Education  Level      46
marital_status         0
city                  52
customer_segment       0
loan_type              0
Loan Amount (INR)    102
tenure Months          0
Monthly Visits        55
debt_to_income        89
Loan Approved?         0
dtype: int64

In [10]:
#7
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
print("Percentage of missing values in each column: ")
print(df.isnull().mean()*100)

Percentage of missing values in each column:
Customer ID          0.000000
Age                  4.625407
Annual Income        5.472313
credit Score         5.016287
Employment-Type      3.908795
Education  Level     2.996743
marital_status       0.000000
city                 3.387622
customer_segment     0.000000
loan_type            0.000000
Loan Amount (INR)    6.644951
tenure Months        0.000000
Monthly Visits       3.583062
debt_to_income       5.798046
Loan Approved?       0.000000
dtype: float64

In [12]:
#8
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
missing_age = df[df["Age"].isna()]
display(missing_age)

,Customer ID,Age,Annual Income,credit Score,Employment-Type,Education Level,marital_status,city,customer_segment,loan_type,Loan Amount (INR),tenure Months,Monthly Visits,debt_to_income,Loan Approved?
21,CUST100354,NaN,302606,726,NaN,Graduate,Single,Bengaluru,Mass,Auto,269320,84,6,0.353,No
29,CUST100989,NaN,650000 INR,778,Self-Employed,Graduate,Divorced,Pune,unknown,Home,1083921,48,5,0.4x,No
100,CUST101150,NaN,100,723,Self-Employed,12th,Married,NaN,Mass,Education,454937,48,five,0.303,Yes
108,CUST100535,NaN,458878,782,Salaried,Diploma,Married,Mumbai,Mass,Auto,549385,36,7,0.279,No
113,CUST101055,NaN,1112464,120,Salaried,Diploma,Married,Kolkata,Mass,Auto,427759,84,3,0.102,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,CUST100392,NaN,570532,766,Contract,Postgraduate,Married,Jaipur,Mass,Home,937612,36,3,0.51,Yes
1430,CUST101368,NaN,519228,728,Business,Postgraduate,Married,Hyderabad,Mass,Home,514679,12,4,0.392,Yes
1498,CUST100700,NaN,658802,772,Contract,Postgraduate,Married,Mumbai,Mass,Auto,257699,24,4,0.584,Yes
1503,CUST100748,NaN,338339,673,Business,Graduate,Married,Chennai,Premium,Business,223704,12,7,0.02,No
1516,CUST100770,NaN,708229,801,Business,NaN,Single,Chennai,Premium,Personal,341664,120,5,0.651,Yes

In [13]:
#9
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
missing_annual_income = df[df["Annual Income"].isna()]
print(missing_annual_income)

     Customer ID Age Annual Income credit Score Employment-Type  \
41    CUST101081  64           NaN          749   Self-Employed
103   CUST101403  35           NaN          660   Self-Employed
119   CUST101095  36           NaN          782   self-employed
132   CUST101048  49           NaN          713        Salaried
144   CUST100530  64           NaN          761        Business
...          ...  ..           ...          ...             ...
1468  CUST100776  65           NaN          667   Self-Employed
1493  CUST101496  41           NaN          662   Self-Employed
1501  CUST100475  50           NaN          802        Contract
1532  CUST100861  66           NaN          686        Contract
1534  CUST101127  61           NaN          731        Salaried

     Education  Level marital_status       city customer_segment  loan_type  \
41            Diploma         Single    Kolkata          Premium   Personal
103          Graduate        Married      Delhi         Affluent       Home
119      Postgraduate        Married  Bengaluru         Affluent       Home
132      Postgraduate         Single  Bengaluru         Affluent       auto
144           Diploma         Single        NaN         Affluent   Business
...               ...            ...        ...              ...        ...
1468         GRADUATE         Single     Mumbai             Mass   Personal
1493             12th         Single    Kolkata         Affluent  Education
1501             12th       Divorced    Kolkata             Mass   Personal
1532            Other        Married      Delhi             Mass   Personal
1534     Postgraduate         Single    Chennai         Affluent  Education

     Loan Amount (INR)  tenure Months Monthly Visits debt_to_income  \
41              254754             24              5          0.327
103                NaN             36              4          0.402
119             225725             60              5          0.341
132             301697             48              7           0.35
144            1182185            120              7           0.02
...                ...            ...            ...            ...
1468            995167             72              3            0.6
1493            693422             48              5          0.272
1501           1488587             36              5          0.023
1532          50000000             36              9          0.084
1534            753995             12              5          0.259

     Loan Approved?
41               No
103              No
119             Yes
132             Yes
144             Yes
...             ...
1468            Yes
1493             No
1501            Yes
1532            Yes
1534             No

[84 rows x 15 columns]

In [16]:
#10
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
before = len(df)
drop_duplicates = df.drop_duplicates()
after = len(drop_duplicates)
print("Duplicate rows removed:",before-after)

Duplicate rows removed: 35

In [17]:
#11
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
display(df["Age"])

0       37.0
1       36.0
2       55.0
3       54.0
4       27.0
        ...
1530    40.0
1531    65.0
1532    66.0
1533    45.0
1534    61.0
Name: Age, Length: 1535, dtype: float64

In [ ]:
#12
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')
df["Annual Income"] = (df["Annual Income"].astype(str).str.strip().str.replace("INR","",regex = False).str.replace("₹","",regex = False))
df.loc[df["Annual Income"].str.endswith("L"),"Annual Income"] = (pd.to_numeric(df.loc[df["Annual Income"].str.endswith("L"),"Annual Income"].str.replace("L","",regex = False),errors = "coerce")*100000)
df["Annual Income"] = pd.to_numeric(df["Annual Income"],errors = "coerce")
display(df["Annual Income"])

TypeError: Invalid value for dtype 'str'. Value should be a string or missing value (or array of those).

In [24]:
# 12
import pandas as pd
df = pd.read_csv("messy_customer_loan_dataset - messy_customer_loan_dataset.csv")
df["Annual Income"] = (
    df["Annual Income"]
    .astype(str)
    .str.strip()
    .str.replace("INR", "", regex=False)
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
)
df["Annual Income"] = df["Annual Income"].str.replace(
    "L", "00000", regex=False
)
df["Annual Income"] = pd.to_numeric(
    df["Annual Income"],
    errors="coerce"
)
display(df[["Annual Income"]])

      Annual Income
0          297809.0
1         1048283.0
2         1043481.0
3          369591.0
4          666989.0
...             ...
1530       477723.0
1531      1394481.0
1532            NaN
1533       543340.0
1534            NaN

[1535 rows x 1 columns]

In [ ]:
#13
import pandas as pd
df = pd.read_csv('messy_customer_loan_dataset - messy_customer_loan_dataset.csv')